### ISSUE TITLE
Eternal Palace timers/settings

### ISSUE THREAD

**Issue by Molkree** [DeadlyBossMods/DBM-BfA#12]
**Describe the bug**
Some timers are slightly off
![image](https://user-images.githubusercontent.com/12860284/153921922-9869bbd6-480a-4d5a-a342-a701ac77c58d.png)
![image](https://user-images.githubusercontent.com/12860284/153921944-d4116fd4-e437-4b26-8a33-6b7ae7b8a5d2.png)

Some settings look weird
![image](https://user-images.githubusercontent.com/12860284/153922037-2e1bc9ce-57b1-4c5b-abdf-c7ed914c09ff.png)
![image](https://user-images.githubusercontent.com/12860284/153922002-51a66a72-7ffe-4895-9828-126245cbc02c.png)

Not sure why this showed up as Unknown and with the right bracket cut off
![image](https://user-images.githubusercontent.com/12860284/153922155-e46bfd23-d8db-4e1b-b06f-9bc0a124237b.png)

**Do you have an error log of what happened?**
[Log](https://gist.github.com/Molkree/88eeb872608808c6cf0cdb9998c76525). It has some garbage in the end (Love is in the Air event sorry).

**Which version of DeadlyBossMods are you using?**
[09226f6](https://github.com/DeadlyBossMods/DBM-BfA/commit/09226f6001dd07fffe2d828b4a00d269ba4e78e9)

**Comment by MysticalOS** [comment]
Fixed in latest commit
